In [2]:
import numpy as np

In [ ]:
##NumPy Arrays

In [3]:
list =[20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [4]:
arr= np.array([20, 27, 9, 12, 31, 17, 4, 50, 39, 35])
arr_multiplied = arr*4
print(arr_multiplied)

[ 80 108  36  48 124  68  16 200 156 140]


In [5]:
mean=np.mean(arr)
print(mean)

24.4


In [8]:
median=np.median(arr)

In [9]:
print(median)

23.5


In [10]:
sd=np.std(arr)
print(sd)

13.828955130450023


In [12]:
min_index = np.argmin(arr)
max_index = np.argmax(arr)
print(min_index)
print(max_index)

6
7


In [13]:
smallest_val_indexed = arr[min_index]
largest_val_indexed = arr[max_index]
print(smallest_val_indexed)
print(largest_val_indexed)

4
50


In [15]:
smallest_val_np_func = np.min(arr)
largest_val_np_func = np.max(arr)

In [16]:
print(smallest_val_np_func)
print(largest_val_np_func)

4
50


In [18]:
boolean_mask=arr>20
print(boolean_mask)

[False  True False False  True False False  True  True  True]


In [19]:
arr_greater_than_20 = arr[boolean_mask]
print(arr_greater_than_20)

[27 31 50 39 35]


In [20]:
## 3.2 2D NumPy Arrays

In [21]:
matrix =[
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]

In [23]:
print(matrix)

[[5, 12, 17, 9], [8, 21, 14, 3], [6, 13, 19, 11]]


In [24]:
#3rows, 4 columns

In [32]:
matrix=np.array(matrix)
third_column=matrix[:, 2]
print(third_column)

[17 14 19]


In [33]:
matrix=np.array(matrix)
second_row = matrix[1, :]
print(second_row)

[ 8 21 14  3]


In [34]:
multiplied_by_2=matrix*2
print(multiplied_by_2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [37]:
column_means=np.mean(matrix, axis=0)
print(column_means)

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [39]:
overall_mean=np.mean(matrix)
print(overall_mean)

11.5


In [40]:
max_row= np.max(matrix, axis=1)
min_col=np.min(matrix, axis=0)
print(max_row)
print(min_col)

[17 21 19]
[ 5 12 14  3]


In [41]:
#4 Prime Star Systems

In [43]:
arr= np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def rows_with_primes(matrix):
    mask = np.array([any(is_prime(x) for x in row) for row in matrix])
    return matrix[mask]
    
result = rows_with_primes(arr)
print(result)

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [44]:
##Checkers!

In [45]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1   
    board[1::2, 1::2] = 1 
    return board

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [46]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, 1::2] = 1  
    board[1::2, ::2] = 1   
    return board
print(reverse_checkerboard())


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
#The Expanding Universe

In [51]:
def expansion(arr,n):
    spacer= ' ' *n
    expanded =[spacer.join(word) for word in arr]
    return np.array(expanded)

universe= np.array(['galaxy', 'cluster'])
print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r']


In [52]:
##Second- Brightest Star

In [55]:
def second_brightest(stars):
    sorted_rows=np.sort(stars, axis=1)
    return sorted_rows[:, -2]

#EG.
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)
print(second_brightest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
